name: Build docker image and push to docker hub #name of workflow

on: 
    push:
        branches:
            - main # This workflow will trigger when there is a push to the main branch


env:
    docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
    docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # The checkout action in GitHub Actions is used to fetch the source code of your repository into the runner environment where your workflow is executing

            - name: Build docker image # The name of the step
              run: docker build -t joshimage:1.0 . #build the docker image with the tag with joshimage as name and tag 1.0 , the  . means current directory for Docker file
            
            - name: login into docker hub
              run: echo $docker_password | docker login -u $docker_username --password-stdin  #using --password-stdin for secure password input. as this is recommend way to provide password for dockerhub

            - name: Tagging local joshimage image built to  repo to be create in dockerhub
              run: docker tag joshimage:1.0 ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-josh:1.0 #Tag the local image with the Docker Hub repository name and docker hub repo not existing it would be created automatically


            - name: push tagged image to docker hub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-josh:1.0 # Push the image to Docker Hub.
