name: Build docker image and push to docker hub #name of workflow

on: 
    push:
        branches:
            - main


env:
    docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
    docker_password: ${{ secrets.DOCKERHUB_PASSWORD }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4 # The checkout action in GitHub Actions is used to fetch the source code of your repository into the runner environment where your workflow is executing

            - name: Build docker image # The name of the step
              run: docker build -t joshimage:1.0 . #build the docker image with the tag with joshimage as name and tag 1.0 , the  . means current folder for Docker file
            
            - name: login into docker hub
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u $docker_username --password-stdin  #using --password-stdin as this is recommend way to provide password for dockerhub

            - name: push image to docker hub
              run: docker push joshimage:1.0
